export const generateRandomName = () => {
  const adjectives = [
    "Cosmic",
    "Random",
    "Mystic",
    "Digital",
    "Dazzling",
    "Swift",
    "Silent",
    "Crystal",
    "Emerald",
    "Golden",
    "Azure",
    "Crimson",
    "Neon",
    "Celestial",
    "Whispering",
    "Radiant",
    "Electric",
    "Phantom",
    "Lunar",
    "Solar",
    "Ancient",
    "Hidden",
    "Enchanted",
    "Quantum",
    "Velvet",
    "Stellar",
    "Frosty",
    "Noble",
    "Wandering",
    "Fiery",
    "Serene",
    "Gleaming",
    "Epic",
    "Twilight",
    "Astral",
    "Vibrant",
    "Shadowy",
    "Eternal",
    "Mighty",
    "Gentle",
  ];

  const nouns = [
    "Otter",
    "Stranger",
    "Voyager",
    "Phoenix",
    "Tiger",
    "Dragon",
    "Eagle",
    "Raven",
    "Shadow",
    "Dreamer",
    "Nomad",
    "Panther",
    "Falcon",
    "Explorer",
    "Guardian",
    "Maverick",
    "Echo",
    "Horizon",
    "Tempest",
    "Comet",
    "Ninja",
    "Wizard",
    "Knight",
    "Wolf",
    "Fox",
    "Pixel",
    "Cosmos",
    "Warden",
    "Spirit",
    "Hunter",
    "Oracle",
    "Sage",
    "Rogue",
    "Champion",
    "Pioneer",
    "Spectre",
    "Whisper",
    "Titan",
    "Nebula",
    "Storm",
  ];

  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];

  return `${randomAdjective} ${randomNoun}`;
};
